<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">$(MSBuildThisFileDirectory)project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\phowlader\.nuget\packages\;C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">6.10.2</NuGetToolVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <SourceRoot Include="C:\Users\phowlader\.nuget\packages\" />
    <SourceRoot Include="C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages\" />
  </ItemGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\element_catalog_cross_section.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\element_catalog_cross_section.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\element_catalog_cross_section.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\element_catalog_cross_section_sketch.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\element_catalog_cross_section_sketch.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\element_catalog_cross_section_sketch.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\element_catalog_cross_section_user.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\element_catalog_cross_section_user.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\element_catalog_cross_section_user.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_1.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_1.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_1.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_10.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_10.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_10.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_11.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_11.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_11.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_13.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_13.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_13.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_15.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_15.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_15.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_2.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_2.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_2.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_3.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_3.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_3.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_4.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_4.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_4.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_5.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_5.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_5.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_6.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_6.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_6.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_7.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_7.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_7.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_8.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_8.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_8.bmp</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_9.bmp" Condition="Exists('$(NuGetPackageRoot)tekla.structures.dialog\2021.0.0\contentFiles\any\net40\Resources\prtyp_tree_9.bmp')">
      <NuGetPackageId>Tekla.Structures.Dialog</NuGetPackageId>
      <NuGetPackageVersion>2021.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>Resources\prtyp_tree_9.bmp</Link>
    </Content>
  </ItemGroup>
</Project>